export const ASSET_LIST = {
    images: [
        ['player', 'assets/player.png'],
        ['monster', 'assets/monster.png'],
        ['epic_monster', 'assets/epic_monster.png'],
        ['warrior', 'assets/images/warrior.png'],
        ['archer', 'assets/images/archer.png'],
        ['healer', 'assets/images/healer.png'],
        ['wizard', 'assets/images/wizard.png'],
        ['summoner', 'assets/images/summoner.png'],
        ['bard', 'assets/images/bard.png'],
        ['mercenary', 'assets/images/warrior.png'],
        ['floor', 'assets/floor.png'],
        ['wall', 'assets/wall.png'],
        ['gold', 'assets/gold.png'],
        ['potion', 'assets/potion.png'],
        ['sword', 'assets/images/shortsword.png'],
        ['shield', 'assets/images/shield.png'],
        ['bow', 'assets/images/bow.png'],
        ['arrow', 'assets/images/arrow.png'],
        ['leather_armor', 'assets/images/leatherarmor.png'],
        ['plate-armor', 'assets/images/plate-armor.png'],
        ['violin-bow', 'assets/images/violin-bow.png'],
        ['skeleton', 'assets/images/skeleton.png'],
        ['pet-fox', 'assets/images/pet-fox.png'],
        ['guardian-hymn-effect', 'assets/images/Guardian Hymn-effect.png'],
        ['courage-hymn-effect', 'assets/images/Courage Hymn-effect.png'],
        // ✨ 아래 파일 경로들을 수정했습니다.
        ['fire-ball', 'assets/images/fire-ball.png'],
        ['ice-ball', 'assets/images/ice-ball-effect.png'],
        ['strike-effect', 'assets/images/strike-effect.png'],
        ['healing-effect', 'assets/images/healing-effect.png'],
        ['purify-effect', 'assets/images/purify-effect.png'],
        ['corpse', 'assets/images/corpse.png'],
        ['parasite', 'assets/images/parasite.png'],
        ['leech', 'assets/images/parasite.png'],
        ['worm', 'assets/images/parasite.png'],
        ['talisman1', 'assets/images/talisman-1.png'],
        ['talisman2', 'assets/images/talisman-2.png'],
    ],
    weapons: [
        ['axe', 'assets/images/axe.png'],
        ['mace', 'assets/images/mace.png'],
        ['staff', 'assets/images/staff.png'],
        ['spear', 'assets/images/spear.png'],
        ['estoc', 'assets/images/Estoc.png'],
        ['scythe', 'assets/images/scythe.png'],
        ['whip', 'assets/images/whip.png'],
        ['dagger', 'assets/images/dagger.png'],
    ],
    emblems: [
        ['emblem_guardian', 'assets/images/emblem_guardian.png'],
        ['emblem_destroyer', 'assets/images/emblem_destroyer.png'],
        ['emblem_devotion', 'assets/images/emblem_devotion.png'],
        ['emblem_conductor', 'assets/images/emblem_conductor.png'],
    ],
};
